### ISSUE TITLE
endpoints_sdwan.yaml is not formatted properly for UX2.0

### ISSUE THREAD

**Issue by tzarski0** [netascode/nac-collector#60]
For UX2.0, when /v1/ APIs are formatted and child is nested more than 1 time, the formatting is wrong. For example currently for transport interface, the formatting is:
```
- name: transport_feature_profile
  endpoint: /v1/feature-profile/sdwan/transport
  children:
  - name: transport_tracker
    endpoint: /tracker
  - name: transport_routing_bgp
    endpoint: /routing/bgp
  - name: transport_wan_vpn_interface_cellular
    endpoint: /wan/vpn/%s/interface/cellular
  - name: transport_routing_ospfv3_ipv4
    endpoint: /routing/ospfv3/ipv4
  - name: transport_t1_e1_controller
    endpoint: /t1-e1-controller
  - name: transport_gps
    endpoint: /gps
  - name: transport_wan_vpn_interface_gre
    endpoint: /wan/vpn/%s/interface/gre
  - name: transport_wan_vpn
    endpoint: /wan/vpn
```

And the proper format should be:
```
- name: transport_feature_profile
  endpoint: /v1/feature-profile/sdwan/transport
  children:
  - name: transport_tracker
    endpoint: /tracker
  - name: transport_routing_bgp
    endpoint: /routing/bgp
  - name: transport_routing_ospfv3_ipv4
    endpoint: /routing/ospfv3/ipv4
  - name: transport_t1_e1_controller
    endpoint: /t1-e1-controller
  - name: transport_gps
    endpoint: /gps
  - name: transport_wan_vpn
    endpoint: /wan/vpn
    children:
    - name: transport_wan_vpn_interface_cellular
      endpoint: /interface/cellular
    - name: transport_wan_vpn_interface_gre
      endpoint: /interface/gre
```
